### ISSUE TITLE
CSW harvest error on OpenTopography HS: 'Invalid parameter value: locator=request'

### ISSUE THREAD

**Issue by kvuppala** [GSA/ckanext-geodatagov#105]
HS: https://catalog.data.gov/dataset/opentopography-csw

I’m not sure what the error is. I don’t believe we have changed anything on our end. Things seem to be up on our end. 
http://opentopo.sdsc.edu/geoportal/csw?service=CSW&version=2.0.2&request=GetCapabilities

Can you let me know what parameters you are using since it says invalid parameter? Thanks!
- Vishu

On Mar 12, 2017, at 7:55 PM, Kishore K. Vuppala wrote:

Hi Vishnu
 
We have been noticing the below error on the harvest jobs,  can you check if anything changed on your end to cause this error.
 
Currently the job is setup to run every week.
Job Report
1 errors 0 added 0 updated 0 deleted
Id	90dc7be4-29a1-4c0a-bac0-23ca09aba3ee
Created	March 11, 2017, 05:42 GMT 
Started	March 11, 2017, 05:47 GMT 
Finished	March 11, 2017, 05:50 GMT 
Status	Finished
Error Summary Only the 20 most frequent errors are shown
Job Errors
Count	Message
1	Error contacting the CSW server: 'Invalid parameter value: locator=request'
Error Report
Job Errors
Error contacting the CSW server: 'Invalid parameter value: locator=request'

**Comment by FuhuXia** [comment]
The source url contains some extra querystring `?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities`. The actual request sent to server is like `/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities&version=2.0.2&request=GetCapabilities&service=CSW`, sever complains about multiple `request` found in the query. 

If we clean up the source url by removing extra querystring, it will be fine. Anyway, I make some code change to clean up extra querystring, so it is not relying on user to clean url.

fixed in https://github.com/GSA/OWSLib/commit/71a43028777bc982d993876d925699af830e2839

**Comment by kalxas** [comment]
@FuhuXia perhaps those fixes should be submitted upstream, to make things easier when we need to upgrade OWSlib in the future

**Comment by kvuppala** [comment]
@kalxas @FuhuXia yes, we plan to push them to upstream soon.
